# target only prod env
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: allow-image-registries
  namespace: openshift-gitops
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            env: prod
  template:
    metadata:
      name: "{{name}}-allow-image-registries"
    spec:
      project: default
      source:
        repoURL: https://github.com/pnminh/gitops-cluster-configs.git
        targetRevision: main
        path: environments/{{metadata.labels.env}}/allow-image-registries
        kustomize:
          namePrefix: '{{name}}-'
      destination:
        namespace: default
        server: "{{server}}" 
      syncPolicy:
        automated:
          selfHeal: false