# target only prod env
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: image-registry-policy
  namespace: openshift-gitops
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            env: prod
  template:
    metadata:
      name: "{{name}}-image-registry-policy"
    spec:
      project: default
      source:
        repoURL: https://github.com/pnminh/gitops-cluster-configs.git
        targetRevision: main
        path: targets/environments/{{metadata.labels.env}}/image-registry-policy
      destination:
        namespace: default
        server: "{{server}}" 
      syncPolicy:
        automated:
          selfHeal: false