# target 1 cluster
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: openshift-pipelines-operator
  namespace: openshift-gitops
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            name: local-cluster
  template:
    metadata:
      name: openshift-pipelines-operator
    spec:
      project: default
      source:
        repoURL: https://github.com/pnminh/gitops-cluster-configs.git
        targetRevision: main
        path: components/openshift-pipelines-operator
        helm:
          valueFiles:
            - "values.yaml"
            - "../../targets/clusters/{{name}}/openshift-pipelines-operator/values.yaml"
      destination:
        namespace: openshift-operators
        server: "{{server}}" 
      syncPolicy:
        automated:
          selfHeal: false