apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: vault-config-operator
  namespace: openshift-gitops
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement # (1)
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: east-gitops-placement
  template:
    metadata:
      name: vault-config-operator
    spec:
      project: default
      source:
        repoURL: https://github.com/pnminh/gitops-cluster-configs.git
        targetRevision: main
        path: components/vault-config-operator
        helm:
          valueFiles:
            - "../../targets/clusters/{{name}}/openshift-pipelines-operator/values.yaml"
      destination:
        namespace: vault-config-operator
        server: "{{server}}" 
      syncPolicy:
        automated:
          selfHeal: false
        syncOptions:
          - CreateNamespace=true 