# target all clusters/values different between environments
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: vault-config-operator
  namespace: openshift-gitops
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: all-gitops-placement
  template:
    metadata:
      name: vault-config-operator
    spec:
      project: default
      source:
        repoURL: https://github.com/pnminh/gitops-cluster-configs.git
        targetRevision: main
        path: components/vault-config-operator
        helm:
          valueFiles:
            - "../../targets/environments/{{env}}/vault-config-operator/values.yaml" #env: label for the cluster
      destination:
        namespace: vault-config-operator
        server: "{{server}}" 
      syncPolicy:
        automated:
          selfHeal: false
        syncOptions:
          - CreateNamespace=true 