{{- if .Values.namespace -}}
apiVersion: apps/v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.name }}
  {{- with .Values.namespace.labels }}
  labels:
      {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.namespace.annotations }}
  annotations:
      {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}