apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-appset
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/pnminh/gitops-cluster-configs.git
      revision: apps
      directories:
      - path: apps/*/environments/dev/dev-1
  template:      
    metadata:
      name: '{{index .path.segments 1}}' 
    spec:
      # The project the application belongs to.
      project: default

      # Source of the application manifests
      source:
        repoURL: https://github.com/pnminh/gitops-cluster-configs.git
        targetRevision: apps
        path: 'apps/{{index .path.segments 1}}'
        helm:
          valueFiles:
            - "values.yaml"
            - "environments/dev/values.yaml"
            - "environments/dev/{{.path.basename}}/values.yaml"
      
      # Destination cluster and namespace to deploy the application
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.path.basenameNormalized}}'

      # Sync policy
      syncPolicy:
        syncOptions:
          - CreateNamespace=true  
        automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
          prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
          selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
      