# bind cluster set to gitops namespace, so Placement resources can have access
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSetBinding
metadata:
  name: east
  namespace: openshift-gitops
spec:
  clusterSet: east
---
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSetBinding
metadata:
  name: west
  namespace: openshift-gitops
spec:
  clusterSet: west